name: Hello World on Push # Name of the workflow

on: [push] # Triggers the workflow on a push event to any branch

jobs:
  say-hello: # Name of the job
    runs-on: ubuntu-latest # The type of runner that the job will run on
    steps:
      - name: Print Hello World # Name of the step
        run: echo "Hello world!" # Runs a single command using the runner's shell
